-- CHARACTER SET utf8mb4
-- COLLATE utf8mb4_unicode_ci;

USE appdb;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- =========================================================
-- ELIMINAR TABLAS SI YA EXISTEN
-- =========================================================
DROP TABLE IF EXISTS COR_REACCIONES_COMENTARIO_TB;
DROP TABLE IF EXISTS COR_COMENTARIOS_TB;
DROP TABLE IF EXISTS COR_PAGOS_TB;
DROP TABLE IF EXISTS COR_RESERVA_SERVICIO_TB;
DROP TABLE IF EXISTS COR_RESERVA_HABITACION_TB; 
DROP TABLE IF EXISTS COR_HABITACION_AMENIDAD_TB;
DROP TABLE IF EXISTS COR_IMAGENES_TIPO_HABITACION_TB;
DROP TABLE IF EXISTS COR_HABITACIONES_TB;
DROP TABLE IF EXISTS COR_SERVICIOS_TB;
DROP TABLE IF EXISTS COR_AMENIDADES_TB;
DROP TABLE IF EXISTS COR_RESERVAS_TB;
DROP TABLE IF EXISTS COR_TIPOS_HABITACION_TB;
DROP TABLE IF EXISTS COR_HOTELES_TB;
DROP TABLE IF EXISTS COR_USUARIOS_TB;

-- =========================================================
-- TABLA: COR_USUARIOS_TB
-- =========================================================
CREATE TABLE COR_USUARIOS_TB (
    ID_USUARIO BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    CORREO VARCHAR(150) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(20) NULL,
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ESTADO_USUARIO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    ROL VARCHAR(20) NOT NULL DEFAULT 'CLIENTE',

    CONSTRAINT UQ_COR_USUARIOS_CORREO UNIQUE (CORREO),
    CONSTRAINT CHK_COR_USUARIOS_ESTADO
        CHECK (ESTADO_USUARIO IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO')),
    CONSTRAINT CHK_COR_USUARIOS_ROL
        CHECK (ROL IN ('CLIENTE', 'ADMIN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_USUARIOS_APELLIDO_NOMBRE
    ON COR_USUARIOS_TB (APELLIDO, NOMBRE);

CREATE INDEX IDX_COR_USUARIOS_ROL
    ON COR_USUARIOS_TB (ROL);

-- =========================================================
-- TABLA: COR_HOTELES_TB
-- =========================================================
CREATE TABLE COR_HOTELES_TB (
    ID_HOTEL BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_HOTEL VARCHAR(150) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    CIUDAD VARCHAR(100) NOT NULL,
    PROVINCIA VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(20) NULL,
    CORREO VARCHAR(150) NULL,
    DESCRIPCION TEXT NULL,
    ESTADO_HOTEL VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',

    CONSTRAINT UQ_COR_HOTELES_NOMBRE UNIQUE (NOMBRE_HOTEL),
    CONSTRAINT CHK_COR_HOTELES_ESTADO
        CHECK (ESTADO_HOTEL IN ('ACTIVO', 'INACTIVO', 'MANTENIMIENTO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_HOTELES_PROVINCIA_CIUDAD
    ON COR_HOTELES_TB (PROVINCIA, CIUDAD);

-- =========================================================
-- TABLA: COR_TIPOS_HABITACION_TB
-- =========================================================
CREATE TABLE COR_TIPOS_HABITACION_TB (
    ID_TIPO_HABITACION BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_HOTEL BIGINT UNSIGNED NOT NULL,
    NOMBRE_TIPO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT NULL,
    CAPACIDAD INT UNSIGNED NOT NULL,
    CANTIDAD_CAMAS INT UNSIGNED NOT NULL,
    PRECIO_BASE DECIMAL(10,2) NOT NULL,
    ESTADO_TIPO_HABITACION VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',

    CONSTRAINT UQ_COR_TIPOS_HABITACION_HOTEL_NOMBRE
        UNIQUE (ID_HOTEL, NOMBRE_TIPO),

    CONSTRAINT UQ_COR_TIPOS_HABITACION_HOTEL_TIPO
        UNIQUE (ID_HOTEL, ID_TIPO_HABITACION),

    CONSTRAINT CHK_COR_TIPOS_HABITACION_CAPACIDAD
        CHECK (CAPACIDAD > 0),

    CONSTRAINT CHK_COR_TIPOS_HABITACION_CAMAS
        CHECK (CANTIDAD_CAMAS > 0),

    CONSTRAINT CHK_COR_TIPOS_HABITACION_PRECIO
        CHECK (PRECIO_BASE >= 0),

    CONSTRAINT CHK_COR_TIPOS_HABITACION_ESTADO
        CHECK (ESTADO_TIPO_HABITACION IN ('ACTIVO', 'INACTIVO')),

    CONSTRAINT FK_COR_TIPOS_HABITACION_HOTEL
        FOREIGN KEY (ID_HOTEL) REFERENCES COR_HOTELES_TB(ID_HOTEL)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_TIPOS_HABITACION_HOTEL
    ON COR_TIPOS_HABITACION_TB (ID_HOTEL);

CREATE INDEX IDX_COR_TIPOS_HABITACION_ESTADO
    ON COR_TIPOS_HABITACION_TB (ESTADO_TIPO_HABITACION);

-- =========================================================
-- TABLA: COR_IMAGENES_TIPO_HABITACION_TB
-- =========================================================
CREATE TABLE COR_IMAGENES_TIPO_HABITACION_TB (
    ID_IMAGEN BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_TIPO_HABITACION BIGINT UNSIGNED NOT NULL,
    URL_IMAGEN VARCHAR(500) NOT NULL,
    DESCRIPCION VARCHAR(255) NULL,
    ORDEN_IMAGEN INT UNSIGNED NOT NULL DEFAULT 1,

    CONSTRAINT UQ_COR_IMG_TIPO_HAB_ORDEN
        UNIQUE (ID_TIPO_HABITACION, ORDEN_IMAGEN),

    CONSTRAINT CHK_COR_IMG_TIPO_HAB_ORDEN
        CHECK (ORDEN_IMAGEN > 0),

    CONSTRAINT FK_COR_IMG_TIPO_HAB_TIPO
        FOREIGN KEY (ID_TIPO_HABITACION) REFERENCES COR_TIPOS_HABITACION_TB(ID_TIPO_HABITACION)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_IMG_TIPO_HAB_TIPO
    ON COR_IMAGENES_TIPO_HABITACION_TB (ID_TIPO_HABITACION);

-- =========================================================
-- TABLA: COR_HABITACIONES_TB
-- =========================================================
CREATE TABLE COR_HABITACIONES_TB (
    ID_HABITACION BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_HOTEL BIGINT UNSIGNED NOT NULL,
    ID_TIPO_HABITACION BIGINT UNSIGNED NOT NULL,
    NUMERO_HABITACION VARCHAR(20) NOT NULL,
    PISO INT NULL,
    ESTADO_HABITACION VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE',
    DESCRIPCION TEXT NULL,

    CONSTRAINT UQ_COR_HABITACIONES_HOTEL_NUMERO
        UNIQUE (ID_HOTEL, NUMERO_HABITACION),

    CONSTRAINT CHK_COR_HABITACIONES_ESTADO
        CHECK (ESTADO_HABITACION IN ('DISPONIBLE', 'OCUPADA', 'MANTENIMIENTO', 'INACTIVA')),

    CONSTRAINT FK_COR_HABITACIONES_HOTEL
        FOREIGN KEY (ID_HOTEL) REFERENCES COR_HOTELES_TB(ID_HOTEL)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT FK_COR_HABITACIONES_TIPO
        FOREIGN KEY (ID_HOTEL, ID_TIPO_HABITACION)
        REFERENCES COR_TIPOS_HABITACION_TB (ID_HOTEL, ID_TIPO_HABITACION)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_HABITACIONES_HOTEL
    ON COR_HABITACIONES_TB (ID_HOTEL);

CREATE INDEX IDX_COR_HABITACIONES_TIPO
    ON COR_HABITACIONES_TB (ID_TIPO_HABITACION);

CREATE INDEX IDX_COR_HABITACIONES_ESTADO
    ON COR_HABITACIONES_TB (ESTADO_HABITACION);

-- =========================================================
-- TABLA: COR_AMENIDADES_TB
-- =========================================================
CREATE TABLE COR_AMENIDADES_TB (
    ID_AMENIDAD BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_AMENIDAD VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT NULL,
    ESTADO_AMENIDAD VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',

    CONSTRAINT UQ_COR_AMENIDADES_NOMBRE UNIQUE (NOMBRE_AMENIDAD),
    CONSTRAINT CHK_COR_AMENIDADES_ESTADO
        CHECK (ESTADO_AMENIDAD IN ('ACTIVO', 'INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_AMENIDADES_ESTADO
    ON COR_AMENIDADES_TB (ESTADO_AMENIDAD);

-- =========================================================
-- TABLA: COR_HABITACION_AMENIDAD_TB
-- =========================================================
CREATE TABLE COR_HABITACION_AMENIDAD_TB (
    ID_HABITACION_AMENIDAD BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_HABITACION BIGINT UNSIGNED NOT NULL,
    ID_AMENIDAD BIGINT UNSIGNED NOT NULL,

    CONSTRAINT UQ_COR_HABITACION_AMENIDAD
        UNIQUE (ID_HABITACION, ID_AMENIDAD),

    CONSTRAINT FK_COR_HAB_AMEN_HABITACION
        FOREIGN KEY (ID_HABITACION) REFERENCES COR_HABITACIONES_TB(ID_HABITACION)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT FK_COR_HAB_AMEN_AMENIDAD
        FOREIGN KEY (ID_AMENIDAD) REFERENCES COR_AMENIDADES_TB(ID_AMENIDAD)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_HABITACION_AMENIDAD_HABITACION
    ON COR_HABITACION_AMENIDAD_TB (ID_HABITACION);

CREATE INDEX IDX_COR_HABITACION_AMENIDAD_AMENIDAD
    ON COR_HABITACION_AMENIDAD_TB (ID_AMENIDAD);

-- =========================================================
-- TABLA: COR_SERVICIOS_TB
-- =========================================================
CREATE TABLE COR_SERVICIOS_TB (
    ID_SERVICIO BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_HOTEL BIGINT UNSIGNED NOT NULL,
    NOMBRE_SERVICIO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    ESTADO_SERVICIO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',

    CONSTRAINT UQ_COR_SERVICIOS_HOTEL_NOMBRE
        UNIQUE (ID_HOTEL, NOMBRE_SERVICIO),

    CONSTRAINT CHK_COR_SERVICIOS_PRECIO
        CHECK (PRECIO >= 0),

    CONSTRAINT CHK_COR_SERVICIOS_ESTADO
        CHECK (ESTADO_SERVICIO IN ('ACTIVO', 'INACTIVO')),

    CONSTRAINT FK_COR_SERVICIOS_HOTEL
        FOREIGN KEY (ID_HOTEL) REFERENCES COR_HOTELES_TB(ID_HOTEL)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_SERVICIOS_HOTEL
    ON COR_SERVICIOS_TB (ID_HOTEL);

CREATE INDEX IDX_COR_SERVICIOS_ESTADO
    ON COR_SERVICIOS_TB (ESTADO_SERVICIO);

-- =========================================================
-- TABLA: COR_RESERVAS_TB
-- =========================================================
CREATE TABLE COR_RESERVAS_TB (
    ID_RESERVA BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO BIGINT UNSIGNED NOT NULL,
    ID_HOTEL BIGINT UNSIGNED NOT NULL,
    FECHA_RESERVA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_CHECK_IN DATE NOT NULL,
    FECHA_CHECK_OUT DATE NOT NULL,
    CANTIDAD_HUESPEDES INT UNSIGNED NOT NULL,
    ESTADO_RESERVA VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    TOTAL_RESERVA DECIMAL(10,2) NOT NULL DEFAULT 0.00,

    CONSTRAINT CHK_COR_RESERVAS_FECHAS
        CHECK (FECHA_CHECK_OUT > FECHA_CHECK_IN),

    CONSTRAINT CHK_COR_RESERVAS_HUESPEDES
        CHECK (CANTIDAD_HUESPEDES > 0),

    CONSTRAINT CHK_COR_RESERVAS_ESTADO
        CHECK (ESTADO_RESERVA IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'FINALIZADA')),

    CONSTRAINT CHK_COR_RESERVAS_TOTAL
        CHECK (TOTAL_RESERVA >= 0),

    CONSTRAINT FK_COR_RESERVAS_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES COR_USUARIOS_TB(ID_USUARIO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT FK_COR_RESERVAS_HOTEL
        FOREIGN KEY (ID_HOTEL) REFERENCES COR_HOTELES_TB(ID_HOTEL)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_RESERVAS_USUARIO
    ON COR_RESERVAS_TB (ID_USUARIO);

CREATE INDEX IDX_COR_RESERVAS_HOTEL
    ON COR_RESERVAS_TB (ID_HOTEL);

CREATE INDEX IDX_COR_RESERVAS_FECHAS
    ON COR_RESERVAS_TB (FECHA_CHECK_IN, FECHA_CHECK_OUT);

CREATE INDEX IDX_COR_RESERVAS_ESTADO
    ON COR_RESERVAS_TB (ESTADO_RESERVA);

-- =========================================================
-- TABLA: COR_RESERVA_HABITACION_TB
-- =========================================================
CREATE TABLE COR_RESERVA_HABITACION_TB (
    ID_RESERVA_HABITACION BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_RESERVA BIGINT UNSIGNED NOT NULL,
    ID_HABITACION BIGINT UNSIGNED NOT NULL,
    PRECIO_NOCHE DECIMAL(10,2) NOT NULL,
    CANTIDAD_NOCHES INT UNSIGNED NOT NULL,
    SUBTOTAL DECIMAL(10,2) NOT NULL,

    CONSTRAINT UQ_COR_RESERVA_HABITACION
        UNIQUE (ID_RESERVA, ID_HABITACION),

    CONSTRAINT CHK_COR_RES_HAB_PRECIO
        CHECK (PRECIO_NOCHE >= 0),

    CONSTRAINT CHK_COR_RES_HAB_NOCHES
        CHECK (CANTIDAD_NOCHES > 0),

    CONSTRAINT CHK_COR_RES_HAB_SUBTOTAL
        CHECK (SUBTOTAL >= 0),

    CONSTRAINT FK_COR_RES_HAB_RESERVA
        FOREIGN KEY (ID_RESERVA) REFERENCES COR_RESERVAS_TB(ID_RESERVA)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT FK_COR_RES_HAB_HABITACION
        FOREIGN KEY (ID_HABITACION) REFERENCES COR_HABITACIONES_TB(ID_HABITACION)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_RESERVA_HABITACION_RESERVA
    ON COR_RESERVA_HABITACION_TB (ID_RESERVA);

CREATE INDEX IDX_COR_RESERVA_HABITACION_HABITACION
    ON COR_RESERVA_HABITACION_TB (ID_HABITACION);

-- =========================================================
-- TABLA: COR_RESERVA_SERVICIO_TB
-- =========================================================
CREATE TABLE COR_RESERVA_SERVICIO_TB (
    ID_RESERVA_SERVICIO BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_RESERVA BIGINT UNSIGNED NOT NULL,
    ID_SERVICIO BIGINT UNSIGNED NOT NULL,
    FECHA_SERVICIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD INT UNSIGNED NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    SUBTOTAL DECIMAL(10,2) NOT NULL,

    CONSTRAINT UQ_COR_RESERVA_SERVICIO
        UNIQUE (ID_RESERVA, ID_SERVICIO, FECHA_SERVICIO),

    CONSTRAINT CHK_COR_RES_SER_CANTIDAD
        CHECK (CANTIDAD > 0),

    CONSTRAINT CHK_COR_RES_SER_PRECIO
        CHECK (PRECIO_UNITARIO >= 0),

    CONSTRAINT CHK_COR_RES_SER_SUBTOTAL
        CHECK (SUBTOTAL >= 0),

    CONSTRAINT FK_COR_RES_SER_RESERVA
        FOREIGN KEY (ID_RESERVA) REFERENCES COR_RESERVAS_TB(ID_RESERVA)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT FK_COR_RES_SER_SERVICIO
        FOREIGN KEY (ID_SERVICIO) REFERENCES COR_SERVICIOS_TB(ID_SERVICIO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_RESERVA_SERVICIO_RESERVA
    ON COR_RESERVA_SERVICIO_TB (ID_RESERVA);

CREATE INDEX IDX_COR_RESERVA_SERVICIO_SERVICIO
    ON COR_RESERVA_SERVICIO_TB (ID_SERVICIO);

CREATE INDEX IDX_COR_RESERVA_SERVICIO_FECHA
    ON COR_RESERVA_SERVICIO_TB (FECHA_SERVICIO);

-- =========================================================
-- TABLA: COR_PAGOS_TB
-- =========================================================
CREATE TABLE COR_PAGOS_TB (
    ID_PAGO BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_RESERVA BIGINT UNSIGNED NOT NULL,
    FECHA_PAGO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MONTO DECIMAL(10,2) NOT NULL,
    METODO_PAGO VARCHAR(30) NOT NULL,
    ESTADO_PAGO VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    REFERENCIA_PAGO VARCHAR(100) NULL,

    CONSTRAINT CHK_COR_PAGOS_MONTO
        CHECK (MONTO >= 0),

    CONSTRAINT CHK_COR_PAGOS_METODO
        CHECK (METODO_PAGO IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'PAYPAL')),

    CONSTRAINT CHK_COR_PAGOS_ESTADO
        CHECK (ESTADO_PAGO IN ('PENDIENTE', 'PAGADO', 'RECHAZADO', 'REEMBOLSADO')),

    CONSTRAINT FK_COR_PAGOS_RESERVA
        FOREIGN KEY (ID_RESERVA) REFERENCES COR_RESERVAS_TB(ID_RESERVA)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_PAGOS_RESERVA
    ON COR_PAGOS_TB (ID_RESERVA);

CREATE INDEX IDX_COR_PAGOS_ESTADO
    ON COR_PAGOS_TB (ESTADO_PAGO);

CREATE INDEX IDX_COR_PAGOS_FECHA
    ON COR_PAGOS_TB (FECHA_PAGO);

-- =========================================================
-- TABLA: COR_COMENTARIOS_TB
-- =========================================================
CREATE TABLE COR_COMENTARIOS_TB (
    ID_COMENTARIO BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_RESERVA BIGINT UNSIGNED NOT NULL,
    CALIFICACION DECIMAL(2,1) NOT NULL,
    COMENTARIO TEXT NOT NULL,
    FECHA_COMENTARIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ESTADO_COMENTARIO VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    RESPUESTA_ADMIN TEXT NULL,
    FECHA_RESPUESTA DATETIME NULL,
    ID_ADMIN_RESPUESTA BIGINT UNSIGNED NULL,

    CONSTRAINT UQ_COR_COMENTARIOS_RESERVA
        UNIQUE (ID_RESERVA),

    CONSTRAINT CHK_COR_COMENTARIOS_CALIFICACION
        CHECK (CALIFICACION >= 1.0 AND CALIFICACION <= 5.0),

    CONSTRAINT CHK_COR_COMENTARIOS_ESTADO
        CHECK (ESTADO_COMENTARIO IN ('PENDIENTE', 'APROBADO', 'SPAM', 'ELIMINADO')),

    CONSTRAINT FK_COR_COMENTARIOS_RESERVA
        FOREIGN KEY (ID_RESERVA) REFERENCES COR_RESERVAS_TB(ID_RESERVA)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT FK_COR_COMENTARIOS_ADMIN_RESPUESTA
        FOREIGN KEY (ID_ADMIN_RESPUESTA) REFERENCES COR_USUARIOS_TB(ID_USUARIO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_COMENTARIOS_ESTADO
    ON COR_COMENTARIOS_TB (ESTADO_COMENTARIO);

CREATE INDEX IDX_COR_COMENTARIOS_FECHA
    ON COR_COMENTARIOS_TB (FECHA_COMENTARIO);

-- =========================================================
-- TABLA: COR_REACCIONES_COMENTARIO_TB
-- Solo LIKE y DISLIKE
-- =========================================================
CREATE TABLE COR_REACCIONES_COMENTARIO_TB (
    ID_REACCION BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_COMENTARIO BIGINT UNSIGNED NOT NULL,
    ID_USUARIO BIGINT UNSIGNED NOT NULL,
    TIPO_REACCION VARCHAR(20) NOT NULL,
    FECHA_REACCION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT UQ_COR_REACCION_USUARIO_COMENTARIO
        UNIQUE (ID_COMENTARIO, ID_USUARIO),

    CONSTRAINT CHK_COR_REACCIONES_TIPO
        CHECK (TIPO_REACCION IN ('LIKE', 'DISLIKE')),

    CONSTRAINT FK_COR_REACCIONES_COMENTARIO
        FOREIGN KEY (ID_COMENTARIO) REFERENCES COR_COMENTARIOS_TB(ID_COMENTARIO)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT FK_COR_REACCIONES_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES COR_USUARIOS_TB(ID_USUARIO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_COR_REACCIONES_COMENTARIO_COMENTARIO
    ON COR_REACCIONES_COMENTARIO_TB (ID_COMENTARIO);

CREATE INDEX IDX_COR_REACCIONES_COMENTARIO_USUARIO
    ON COR_REACCIONES_COMENTARIO_TB (ID_USUARIO);

-- =========================================================
-- INSERTS SEMILLA PARA HOTELES
-- =========================================================
INSERT INTO COR_HOTELES_TB (
    NOMBRE_HOTEL,
    DIRECCION,
    CIUDAD,
    PROVINCIA,
    TELEFONO,
    CORREO,
    DESCRIPCION,
    ESTADO_HOTEL
) VALUES
(
    'Hotel Coral Puntarenas',
    'Paseo de los Turistas, frente al mar',
    'Puntarenas',
    'Puntarenas',
    '2661-0001',
    'puntarenas@hotelcoral.com',
    'Sede Hotel Coral ubicada en Puntarenas.',
    'ACTIVO'
),
(
    'Hotel Coral Limon',
    'Cerca del centro y zona costera',
    'Limon',
    'Limon',
    '2758-0002',
    'limon@hotelcoral.com',
    'Sede Hotel Coral ubicada en Limon.',
    'ACTIVO'
),
(
    'Hotel Coral Guanacaste',
    'Ruta principal hacia la playa',
    'Liberia',
    'Guanacaste',
    '2666-0003',
    'guanacaste@hotelcoral.com',
    'Sede Hotel Coral ubicada en Guanacaste.',
    'ACTIVO'
);

SET FOREIGN_KEY_CHECKS = 1;


INSERT INTO COR_USUARIOS_TB
(
    NOMBRE,
    APELLIDO,
    CORREO,
    CONTRASENA,
    TELEFONO,
    ESTADO_USUARIO,
    ROL
)
VALUES
(
    'Admin',
    'Principal',
    'admin@admin.com',
    '$2y$10$NA2gTU2M1Q3zHcRatlvDwu87CjpkPkKX8f.xTslNFLzvHSWfyxIFC',
    '00001111',
    'ACTIVO',
    'ADMIN'
);